[package]
name = "nanosh"
version = "0.1.0"
authors = ["matsuyoshi30 <sfbgwm30@gmail.com>"]
edition = "2018"

[dependencies]
ctrlc = { version = "3.0", features = ["termination"] }
shlex = "0.1.0"
dirs = "1.0"